### ISSUE TITLE
Get page with depth fails because of undefined errors

### ISSUE THREAD

**Issue by arjunadotfusion** [agility/agility-sync-sdk#5]
A Call like the one below often fails.

```
await syncClient.store.getPage({
        languageCode: 'en-us',
        pageID: currentPage.pageID,
        depth: 3
      })
```

The cause of failure seems to be the fact that the `expandContentItem` method doesn't check for undefined values here :
https://github.com/agility/agility-sync-sdk/blob/d6a812dcdf3a01983aace64e0e76c5244f15fb76/src/store-interface.js#L123

This causes strange issues when checking through 
https://github.com/agility/agility-sync-sdk/blob/d6a812dcdf3a01983aace64e0e76c5244f15fb76/src/store-interface.js#L124

if the fieldvalue.contentId is null or undefined, `null > 0` and `undefined. > 0` will resolve to false

but if fieldvalue is null it will bomb

here is the error stack:

```
(node:47837) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'contentid' of null
    at _callee10$ (/Users/arjuna/Work/applied-radiology-2020/node_modules/@agility/content-sync/dist/agility-sync-sdk.node.js:9390:24)
    at tryCatch (/Users/arjuna/Work/applied-radiology-2020/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/Users/arjuna/Work/applied-radiology-2020/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/Users/arjuna/Work/applied-radiology-2020/node_modules/regenerator-runtime/runtime.js:118:21)
    at store_interface_asyncGeneratorStep (/Users/arjuna/Work/applied-radiology-2020/node_modules/@agility/content-sync/dist/agility-sync-sdk.node.js:9267:117)
    at _next (/Users/arjuna/Work/applied-radiology-2020/node_modules/@agility/content-sync/dist/agility-sync-sdk.node.js:9267:470)
    at /Users/arjuna/Work/applied-radiology-2020/node_modules/@agility/content-sync/dist/agility-sync-sdk.node.js:9267:667
    at new Promise (<anonymous>)
    at /Users/arjuna/Work/applied-radiology-2020/node_modules/@agility/content-sync/dist/agility-sync-sdk.node.js:9267:376
    at expandContentItem (/Users/arjuna/Work/applied-radiology-2020/node_modules/@agility/content-sync/dist/agility-sync-sdk.node.js:9406:186)
(node:47837) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```

**Comment by jamesvidler** [comment]
Thank you for notifying us about this! We've just released an updated package to resolve this https://www.npmjs.com/package/@agility/content-sync, version 0.19
